[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF ./src"
  [build.environment]
    Content-Security-Policy = "script-src 'self' 'unsafe-inline' 'unsafe-eval' https://*.googleapis.com https://*.gstatic.com; img-src 'self' data: https://*.googleapis.com https://*.gstatic.com https://*.supabase.co https://images.unsplash.com https://flagcdn.com; connect-src 'self' https://*.googleapis.com https://*.gstatic.com https://*.supabase.co; object-src 'none';"
    VITE_GOOGLE_MAPS_API_KEY = "$VITE_GOOGLE_MAPS_API_KEY"

[dev]
  command = "npm run dev"
  targetPort = 5173

[functions.environment]
  RESEND_API_KEY = "$RESEND_API_KEY"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200


[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
